test_hello:
  handler: src/handlers/hello.handler
  events:
    - http:
        path: /test/hello
        method: get

test_dbconfig:
  handler: src/handlers/dbconfig.handler
  events:
    - http:
        path: /test/database
        method: get

